#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-pr-check

on: 
  push:
    branches:
      - GA-s390x

jobs:    
  build-run-on-action:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    
    strategy:
      matrix:
        include:
          - arch: s390x
            distro: ubuntu20.04
    steps:
    - uses: actions/checkout@v2
    - name : Build with Maven
      uses: uraimo/run-on-arch-action@master
      with:  
       arch: ${{ matrix.arch }}
       distro: ${{ matrix.distro }}
       shell: /bin/bash
       run: |
        apt-get update -y 
        apt-get install -y curl unzip sudo
        mkdir -p /opt/adoptopenjdk/java
        curl -SL -o adoptjdk.tar.gz https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk12u-2019-09-10-13-21/OpenJDK12U-jdk_s390x_linux_openj9_2019-09-10-13-21.tar.gz
        tar -zxvf adoptjdk.tar.gz -C /opt/adoptopenjdk/java --strip-components 1
        export JAVA_HOME=/opt/adoptopenjdk/java
        export PATH=$JAVA_HOME/bin:$PATH
        curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
        unzip -d /usr/share maven.zip
        rm maven.zip
        ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
        export M2_HOME=/usr/share/apache-maven-3.6.3
        export PATH=/usr/share/apache-maven-3.6.3/bin:$PATH
        export MAVEN_OPTS="-Xmx2048m"
        mvn -B -X clean install -U -Pintegration
