#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-pr-check

on: 
  push:
    branches:
      - GA-s390x

jobs:    
  build-run-on-action:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    
    strategy:
      matrix:
        arch:
          - s390x
          - amd64
          
    steps:
      - uses: actions/checkout@v2
      - name: cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Update System
        run: sudo apt-get update -y
      - name: Install qemu
        run: sudo apt-get install -y --no-install-recommends qemu-user-static
      - name: Experimental Docker
        run: sudo cp .github/workflows/experimental-docker.json /etc/docker/daemon.json
      - name: Restart Docker
        run: sudo systemctl restart docker.service
      - name: Pull docker image
        run: docker pull ${{ matrix.arch }}/ubuntu:20.04 || true
      - name: Build inside Docker
        run: | 
            sudo apt-get install -y selinux selinux-tools
            setenforce 0
            docker run --rm -v .github/workflows/build-native-maven.sh:/work ${{ matrix.arch }}/ubuntu:20.04 /work/.github/workflows/build-native-maven.sh 
  
