#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-pr-check

on: 
  push:
    branches:
      - GA-native-build-s390x

jobs:    
  build-run-on-action:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    
    strategy:
      matrix:
        include:
          - arch: s390x
            distro: ubuntu20.04
    steps:
    - uses: actions/checkout@v2
    - name : Build with Maven
      uses: aditijadhav38/run-on-arch-action@master
      with:  
       arch: ${{ matrix.arch }}
       distro: ${{ matrix.distro }}
       shell: /bin/bash
       run: |
        apt-get update
        apt-get --no-install-recommends install -y curl unzip sudo openjdk-11-jdk-headless maven
        export MAVEN_OPTS="-Xmx2048m"
        java -version 
