#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-pr-check

on: 
  push:
    branches:
      - GA-native-build-s390x

jobs:    
  build-run-on-action:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    
    strategy:
      matrix:
        include:
          - arch: s390x
            distro: ubuntu20.04
    steps:
    - uses: actions/checkout@v2
    - name : Build with Maven
      uses: uraimo/run-on-arch-action@2.0.9
      with:  
       arch: ${{ matrix.arch }}
       distro: ${{ matrix.distro }}
       shell: /bin/bash
       install: |
        apt-get -q -y update
        apt-get install -q -y curl unzip wget maven
       run: |
        export MAVEN_OPTS="-Xmx2048m"
        wget http://www.java.net/download/openjdk/jdk8/promoted/b132/openjdk-8-src-b132-03_mar_2014.zip
        unzip openjdk-8-src-b132-03_mar_2014.zip
        cd openjdk/hotspot/src/share/tools/hsdis
        wget http://ftp.heanet.ie/mirrors/gnu/binutils/binutils-2.23.2.tar.gz
        tar -xzf binutils-2.23.2.tar.gz
        sudo apt-get install -q -y libgmp-dev libmpfr-dev libmpc-dev g++-multilib
        make BINUTILS=binutils-2.23.2 ARCH=s390x
        cp build/linux-s390x/hsdis-s390x.so ~/java8/jre/lib/s390x/server
        java -version
