#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-pr-check

on: 
  push:
    branches:
      - GA-native-build-s390x

jobs:    
  build-run-on-action:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    
    strategy:
      matrix:
        include:
          - arch: s390x
            distro: ubuntu20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
        ${{ runner.os }}-maven-  
    - name : Build with Maven
      uses: uraimo/run-on-arch-action@v2.0.8
      with:  
       arch: ${{ matrix.arch }}
       distro: ${{ matrix.distro }}
       shell: /bin/bash
       run: |
        apt-get update
        apt-get install -y curl unzip tar wget
        wget https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09_openj9-0.20.0/OpenJDK8U-jdk_s390x_linux_openj9_8u252b09_openj9-0.20.0.tar.gz
        tar -xvf OpenJDK8U-jdk_s390x_linux_openj9_8u252b09_openj9-0.20.0.tar.gz
        export JAVA_HOME=$PWD/jdk8u252-b09
        export PATH=$JAVA_HOME/bin:$PATH
        export JAVA_TOOL_OPTIONS='-Xmx2g'
        curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
        unzip -d /usr/share maven.zip
        rm maven.zip
        ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
        echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
        mvn -B clean install -U -Pintegration
